# Generated by Django 4.2 on 2026-04-29 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('numero_horas', models.IntegerField()),
                ('creditos', models.IntegerField(default=0)),
                ('estado', models.BooleanField(default=True)),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='accounts.docente')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='accounts.curso')),
            ],
            options={
                'unique_together': {('nombre', 'grado')},
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('tarea', 'Tarea'), ('examen', 'Examen'), ('proyecto', 'Proyecto'), ('participacion', 'Participación'), ('otro', 'Otro')], default='tarea', max_length=20)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('ponderacion', models.FloatField(default=0)),
                ('es_plantilla', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='courses.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=10)),
                ('fecha_matricula', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('retirado', 'Retirado'), ('culminado', 'Culminado')], default='activo', max_length=20)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='courses.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='accounts.estudiante')),
            ],
            options={
                'unique_together': {('estudiante', 'curso', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='courses.actividad')),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='accounts.estudiante')),
            ],
            options={
                'unique_together': {('estudiante', 'actividad')},
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('P', 'Presente'), ('F', 'Falta'), ('L', 'Licencia')], default='P', max_length=1)),
                ('motivo', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='courses.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='accounts.estudiante')),
                ('registrada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('estudiante', 'curso', 'fecha')},
            },
        ),
    ]
