# Generated by Django 4.2 on 2026-05-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_actividad_trimestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='fecha',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='trimestre',
            field=models.CharField(choices=[('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3')], db_index=True, default='T1', max_length=2),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('P', 'Presente'), ('F', 'Falta'), ('L', 'Licencia')], db_index=True, default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('retirado', 'Retirado'), ('culminado', 'Culminado')], db_index=True, default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='materia',
            name='estado',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
