# Generated by Django 4.2 on 2026-04-29 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.CharField(choices=[('matricula', 'Matrícula'), ('pension', 'Pensión'), ('matricula_pension', 'Matrícula + Pensión'), ('actividades', 'Actividades Extras'), ('otros', 'Otros')], max_length=20)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido'), ('parcial', 'Pago Parcial'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('numero_comprobante', models.CharField(blank=True, max_length=50)),
                ('metodo_pago', models.CharField(blank=True, max_length=50)),
                ('referencia_pago', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='accounts.estudiante')),
            ],
            options={
                'ordering': ['-fecha_vencimiento'],
            },
        ),
    ]
