# Generated by Django 4.2 on 2026-05-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='concepto',
            field=models.CharField(choices=[('matricula', 'Matrícula'), ('pension', 'Pensión'), ('matricula_pension', 'Matrícula + Pensión'), ('actividades', 'Actividades Extras'), ('otros', 'Otros')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido'), ('parcial', 'Pago Parcial'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_vencimiento',
            field=models.DateField(db_index=True),
        ),
    ]
