# Generated by Django 4.2 on 2026-05-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_estudiante_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], db_index=True, default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('retirado', 'Retirado'), ('egresado', 'Egresado')], db_index=True, default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('docente', 'Docente'), ('padre', 'Padre/Tutor'), ('administrativo', 'Administrativo'), ('directivo', 'Directivo')], db_index=True, default='estudiante', max_length=20),
        ),
    ]
