# Generated by Django 4.2 on 2026-05-06 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_docente_estado_alter_estudiante_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnioAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionTrimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3')], max_length=2)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimestres', to='accounts.anioacademico')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('anio', 'nombre')},
            },
        ),
    ]
